#!/usr/bin/env node
// Generates dist/tokens.css from tokens/tokens.json. No dependencies.
//
// Every custom property is emitted on BOTH :host and :root. The Chrome
// extension renders inside a shadow root on third-party pages, where :root
// refers to the host page's <html> and never reaches our shadow tree - so
// :host alone carries the tokens there, and :root carries them on the web app.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.join(here, '..');
const tokens = JSON.parse(fs.readFileSync(path.join(pkgRoot, 'tokens/tokens.json'), 'utf8'));

const PREFIX = '--aib';

/** Resolve "{brand.cobalt}" style references against the token tree. */
function resolve(value, seen = new Set()) {
  if (typeof value !== 'string') return value;
  const ref = value.match(/^\{([^}]+)\}$/);
  if (!ref) return value;
  const key = ref[1];
  if (seen.has(key)) throw new Error(`Circular token reference: ${key}`);
  seen.add(key);
  const target = key.split('.').reduce((node, part) => node?.[part], tokens);
  if (target === undefined) throw new Error(`Unknown token reference: {${key}}`);
  return resolve(target, seen);
}

const decls = (group, entries) =>
  Object.entries(entries)
    .map(([name, value]) => `  ${PREFIX}-${group ? group + '-' : ''}${name}: ${resolve(value)};`)
    .join('\n');

const dropComments = (obj) =>
  Object.fromEntries(Object.entries(obj).filter(([k]) => !k.startsWith('$')));

const base = [
  decls('', dropComments(tokens.brand)),
  decls('', dropComments(tokens.palette)),
  decls('font', tokens.font),
  decls('text', tokens.text),
  decls('space', tokens.space),
  decls('radius', tokens.radius),
  decls('shadow', tokens.shadow),
].join('\n\n');

const light = decls('', tokens.semantic.light);
const dark = decls('', tokens.semantic.dark);

const css = `/* Generated by packages/design-system/scripts/build-tokens.mjs - do not edit.
   Edit tokens/tokens.json and run \`npm run build:tokens\` from the repo root. */

:host, :root {
${base}

  /* Semantic roles - light is the default so no token is defined only
     inside a media query. */
${light}
}

@media (prefers-color-scheme: dark) {
  :host(:not([data-theme="light"])), :root:not([data-theme="light"]) {
${dark}
  }
}

:host([data-theme="dark"]), :root[data-theme="dark"] {
${dark}
}

:host([data-theme="light"]), :root[data-theme="light"] {
${light}
}
`;

fs.mkdirSync(path.join(pkgRoot, 'dist'), { recursive: true });
fs.writeFileSync(path.join(pkgRoot, 'dist/tokens.css'), css);

// The same CSS as a module. The web app can just link tokens.css, but the
// extension has to inject the tokens *into* a shadow root on a page it does
// not control, which needs the text at runtime.
fs.writeFileSync(
  path.join(pkgRoot, 'dist/tokens.js'),
  `// Generated - do not edit.\nexport const tokensCss = ${JSON.stringify(css)};\n`
);

const count = css.match(/--aib-/g).length;
console.log(`design-system: wrote dist/tokens.css (${count} declarations)`);
